name: Build-Test-Deploy

on:
  push:
    branches: [main]

jobs:

  Lint-Testing-Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/NextJS-Demo/hello-world
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run build
              npm run test
              npm run lint
  Deploying-Docker-to-Heroku:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/NextJS-Demo/hello-world
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nextjs-demo-apps" #Must be unique in Heroku
          heroku_email: "danielsanchez1502@gmail.com"
          usedocker: true
