name: Build-Test-Deploy

on:
  push:
    branches: [main]

jobs:

  Lint-Testing-Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/NextJS-Demo/hello-world
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run build
              npm run test
              npm run lint
  Deploying-Docker-to-Heroku:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/NextJS-Demo/hello-world
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nextjs-demo-apps" #Must be unique in Heroku
          heroku_email: "danielsanchez1502@gmail.com"
          dockerfile_path: ./frontend/NextJS-Demo/hello-world/Dockerfile
